// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError('DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhVyJ3htflB8AHdVUDQg5_D1exIKCxMHM',
    appId: '1:853198079561:web:4ffbc3919ee01452522198',
    messagingSenderId: '853198079561',
    projectId: 'sign-in-d7c92',
    authDomain: 'sign-in-d7c92.firebaseapp.com',
    storageBucket: 'sign-in-d7c92.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCv8SuWIh0xehoVrMUDN55_xz9qzTXtcI0',
    appId: '1:853198079561:android:c70a5e238dcbfa55522198',
    messagingSenderId: '853198079561',
    projectId: 'sign-in-d7c92',
    storageBucket: 'sign-in-d7c92.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRrEo0BjFXTpKxkkte77eoqFJlO8c8Pjo',
    appId: '1:853198079561:ios:ef330c4a65c388c0522198',
    messagingSenderId: '853198079561',
    projectId: 'sign-in-d7c92',
    storageBucket: 'sign-in-d7c92.firebasestorage.app',
    iosBundleId: 'com.example.flutterIntroBootcampProject',
  );
}
